# Use the official Python image from the Docker Hub
ARG BASE_IMAGE=binhex/arch-code-server
FROM ${BASE_IMAGE}

LABEL maintainer="marmotcai@163.com"

ENV DATA_PATH="/app/devspace"
USER root

# ENV HTTPS_PROXY=registry.atoml.net:30090
RUN curl -L https://github.com/docker/compose/releases/download/v2.29.5/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

#######################################################

EXPOSE 80
