
ARG RUNNER_IMAGE=python:3.10.14-slim-bookworm
# 第三阶段：应用环境
FROM ${RUNNER_IMAGE} as app

RUN apt-get clean && apt-get update && apt-get install -y git

ARG GIT_USERNAME=test
ARG GIT_PASSWORD=test
ARG GIT_URL_PREFIX=172.16.14.66:8300/caijun

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir poetry

RUN pip3 install --no-cache-dir git+http://${GIT_USERNAME}:${GIT_PASSWORD}@${GIT_URL_PREFIX}/slines-core.git
RUN pip3 install --no-cache-dir git+http://${GIT_USERNAME}:${GIT_PASSWORD}@${GIT_URL_PREFIX}/slines-plugins.git@dev

# 暴露端口
EXPOSE 8194