# Use the official Python image from the Docker Hub
ARG BASE_IMAGE=binhex/arch-code-server
FROM ${BASE_IMAGE}

LABEL maintainer="marmotcai@163.com"

ENV DATA_PATH="/app/devspace"
USER root

#######################################################

EXPOSE 80
