# Use the official Python image from the Docker Hub
ARG BASE_IMAGE=ubuntu/squid:latest
FROM ${BASE_IMAGE}

LABEL maintainer="marmotcai@163.com"

COPY ./ssrf_proxy/squid.conf.template /etc/squid/squid.conf.template

WORKDIR /app
COPY ./ssrf_proxy/docker-entrypoint.sh .
RUN sed -i 's/\r$$//' ./docker-entrypoint.sh
RUN chmod +x ./docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
