# Use the official Python image from the Docker Hub
ARG BASE_IMAGE=ubuntu/squid:latest
FROM ${BASE_IMAGE}

LABEL maintainer="marmotcai@163.com"

COPY ./docker/ssrf_proxy/squid.conf.template /etc/squid/squid.conf.template
COPY ./docker/ssrf_proxy/docker-entrypoint.sh /docker-entrypoint-mount.sh

RUN cp /docker-entrypoint-mount.sh /docker-entrypoint.sh
RUN sed -i 's/\r$$//' /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

CMD ["./docker-entrypoint.sh"]
